export const ALERTS_PUSH = 'ALERTS_PUSH';
export const ALERTS_POP = 'ALERTS_POP';

export const AUDIENCES_SET_ITEMS = 'AUDIENCES_SET_ITEMS';
export const AUDIENCES_CREATE_ITEM = 'AUDIENCES_CREATE_ITEM';
export const AUDIENCES_UPDATE_ITEM = 'AUDIENCES_UPDATE_ITEM';
export const AUDIENCES_REMOVE_ITEM = 'AUDIENCES_REMOVE_ITEM';

export const AUTH_SET_STATUS = 'AUTH_SET_STATUS';

export const CONFLICTS_SET_ITEMS = 'CONFLICTS_SET_ITEMS';
export const CONFLICTS_REMOVE_ITEM = 'CONFLICTS_REMOVE_ITEM';

export const GRADES_SET_ITEMS = 'GRADES_SET_ITEMS';
export const GRADES_CREATE_ITEM = 'GRADES_CREATE_ITEM';
export const GRADES_UPDATE_ITEM = 'GRADES_UPDATE_ITEM';
export const GRADES_REMOVE_ITEM = 'GRADES_REMOVE_ITEM';

export const GROUPS_APPEND_ITEMS = 'GROUPS_APPEND_ITEMS';
export const GROUPS_REMOVE_ITEMS = 'GROUPS_REMOVE_ITEMS';
export const GROUPS_CREATE_ITEM = 'GROUPS_CREATE_ITEM';
export const GROUPS_UPDATE_ITEM = 'GROUPS_UPDATE_ITEM';
export const GROUPS_REMOVE_ITEM = 'GROUPS_REMOVE_ITEM';

export const LESSONS_APPEND_ITEMS = 'LESSONS_APPEND_ITEMS';
export const LESSONS_REMOVE_ITEMS = 'LESSONS_REMOVE_ITEMS';
export const LESSONS_SORT_ITEMS = 'LESSONS_SORT_ITEMS';
export const LESSONS_CREATE_ITEM = 'LESSONS_CREATE_ITEM';
export const LESSONS_REMOVE_ITEM = 'LESSONS_REMOVE_ITEM';

export const SETTINGS_SET_WEEK = 'SETTINGS_SET_WEEK';

export const SUBJECTS_SET_ITEMS = 'SUBJECTS_SET_ITEMS';
export const SUBJECTS_CREATE_ITEM = 'SUBJECTS_CREATE_ITEM';
export const SUBJECTS_UPDATE_ITEM = 'SUBJECTS_UPDATE_ITEM';
export const SUBJECTS_REMOVE_ITEM = 'SUBJECTS_REMOVE_ITEM';

export const TEACHERS_SET_ITEMS = 'TEACHERS_SET_ITEMS';
export const TEACHERS_CREATE_ITEM = 'TEACHERS_CREATE_ITEM';
export const TEACHERS_UPDATE_ITEM = 'TEACHERS_UPDATE_ITEM';
export const TEACHERS_REMOVE_ITEM = 'TEACHERS_REMOVE_ITEM';

export const TIMES_SET_ITEMS = 'TIMES_SET_ITEMS';
